#!/bin/sh
#设置系统语言为中文呢
export LANG=zh_CN.UTF-8

#设置ibus输入法环境变量
#export GTK_IM_MODULE=ibus
#export QT_IM_MODULE=ibus
#export XMODIFIERS=\@im=ibus
#export INPUT_METHOD=ibus
#export SDL_IM_MODULE=ibus
#export GLFW_IM_MODULE=ibus

#fcitx5环境变量
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=\@im=fcitx5
export INPUT_METHOD=fcitx5
export SDL_IM_MODULE=fcitx5
export GLFW_IM_MODULE=fcitx5



userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# 开机自启动的软件

#设置半透明
picom -cGbf &
#输入法
fcitx5 -d &
#ibus-daemon --xim -d &
#设置壁纸
# /bin/bash ~/.config/scripts/wp-autochange.sh &
python -u ~/.config/scripts/changewp.py &

#状态栏
slstatus &
# dwmstatus 2>&1 >/dev/null &

#网络托盘
nm-applet &
exec dwm
